pam_sss: fix missing initializer
Fix the following error introduced by:
3ed254765fc92e9cc9e4c35335818eaf1256e0d6

```
/home/pbrezina/workspace/sssd/src/sss_client/pam_sss.c: In function ‘prompt_sc_pin’:
/home/pbrezina/workspace/sssd/src/sss_client/pam_sss.c:1839:41: error: missing initializer for field ‘next’ of ‘struct cert_auth_info’ [-Werror=missing-field-initializers]
                                         NULL, NULL, NULL, NULL, NULL };
                                         ^~~~
/home/pbrezina/workspace/sssd/src/sss_client/pam_sss.c:132:28: note: ‘next’ declared here
     struct cert_auth_info *next;

```

Reviewed-by: Alexey Tikhonov <atikhono@redhat.com>
(cherry picked from commit a08d4741cd5d2ecea44eb590e881baf2071e34d2)